###############################################################################
# 02_HELP_severity_overlap_diagnostics.R
#
# Reviewer-requested description of the amount of confounding / overlap
# generated by the four final HELP mechanisms.
#
# This does NOT alter the main simulation settings.
###############################################################################

if (!exists("BG", inherits = FALSE)) 
source("99_HELP_diagnostic_helpers.R")

n_rep <- 1000L
source_target <- mean(data$dayslink[data$treat == 0]) -
  mean(data$dayslink[data$treat == 1])

cat("\nGenerating final HELP scenarios for diagnostics...\n")

set.seed(101010L)
list_additional <- newdatamahal_normal2(
  data = data,
  bern = rbinom(n_rep, 1, 0.60),
  n = rep(60L, n_rep),
  q = rep(0.90, n_rep),
  BG = BG
)

set.seed(101010L)
list_decmah <- decoupling_mahalanobis2(
  data = data,
  N = rep(150L, n_rep),
  p = 0.54,
  x1 = "daysanysub",
  resampling = 0,
  n_res = 1000,
  BG = BG
)

set.seed(101010L)
list_perfect <- observational_help2(
  data = data,
  n = rep(1000L, n_rep),
  BG = BG,
  gamma = 1.25
)

set.seed(101010L)
list_deccov <- decoupling_covariate(
  data = data,
  N = rep(90L, n_rep),
  p = 0.50,
  x = "daysanysub",
  BG = BG
)

targets <- list(
  "Additional Sampling" = rep(source_target, n_rep),
  "Decoupling Mahalanobis" = vapply(list_decmah, function(d) attr(d, "rct_target"), numeric(1)),
  "Perfect Knowledge" = vapply(list_perfect, function(d) attr(d, "rct_target"), numeric(1)),
  "Decoupling Covariate" = vapply(list_deccov, function(d) attr(d, "rct_target"), numeric(1))
)

scenario_lists <- list(
  "Additional Sampling" = list_additional,
  "Decoupling Mahalanobis" = list_decmah,
  "Perfect Knowledge" = list_perfect,
  "Decoupling Covariate" = list_deccov
)

all_rep <- list()
all_smd <- list()
all_sum <- list()

for (sc in names(scenario_lists)) {
  target_sc <- targets[[sc]]
  # HELP_diag_list accepts a scalar target, so use the mean paired target for the
  # compact severity table; replicate-specific targets are saved separately below.
  z <- HELP_diag_list(
    scenario_lists[[sc]],
    scenario = sc,
    source_data = data,
    target = mean(target_sc)
  )
  all_rep[[sc]] <- z$replicates
  all_smd[[sc]] <- z$smd
  all_sum[[sc]] <- HELP_summarise_diag(z$replicates)
}

replicates <- do.call(rbind, all_rep)
smd_by_covariate <- do.call(rbind, all_smd)
summary_table <- do.call(rbind, all_sum)

write.csv(summary_table,
          "results/HELP_supplement_severity_overlap_summary.csv",
          row.names = FALSE)
write.csv(replicates,
          "results/HELP_supplement_severity_overlap_replicates.csv",
          row.names = FALSE)
write.csv(smd_by_covariate,
          "results/HELP_supplement_SMD_by_covariate.csv",
          row.names = FALSE)

target_table <- data.frame(
  replicate = seq_len(n_rep),
  Additional_Sampling = targets[["Additional Sampling"]],
  Decoupling_Mahalanobis = targets[["Decoupling Mahalanobis"]],
  Perfect_Knowledge = targets[["Perfect Knowledge"]],
  Decoupling_Covariate = targets[["Decoupling Covariate"]]
)
write.csv(target_table,
          "results/HELP_supplement_targets.csv",
          row.names = FALSE)

cat("\nHELP severity / overlap summary:\n")
print(summary_table, row.names = FALSE)
